version: '3'

services:
    api:
        build: .
        volumes:
          - ./db.json:/opt/data-copliot/vami
        environment:
          - CONFIG_ENV=testing
          - MOCHA_REPORTER=spec

    web:
        build: www/.
        volumes:
            - ./www:/www
        depends_on:
            - api
        ports:
            - 8081:3000

    web-server:
        image: nginx
        volumes:
            - ./config/nginx/site-enabled/default:/etc/nginx/conf.d/default.conf
            - ./www:/var/www
        depends_on:
            - web
        ports:
            - 8082:8082
